version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - crowded-docker-network
    volumes:
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - elastic:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - "5601:5601"
    networks:
      - crowded-docker-network
#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass d2f3db53e6aefddcfdf5c0f2cd36f95517356e9b
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - crowded-docker-network
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

networks:
  crowded-docker-network:
    external: true
volumes:
  elastic:
    driver: local
  mongodb_data_container:
