module.exports = {
    title_en: [
        "Afghan",
        "Albanian",
        "Algerian",
        "American",
        "Andorran",
        "Angolan",
        "Antiguans",
        "Argentinean",
        "Armenian",
        "Australian",
        "Austrian",
        "Azerbaijani",
        "Bahamian",
        "Bahraini",
        "Bangladeshi",
        "Barbadian",
        "Barbudans",
        "Batswana",
        "Belarusian",
        "Belgian",
        "Belizean",
        "Beninese",
        "Bhutanese",
        "Bolivian",
        "Bosnian",
        "Brazilian",
        "British",
        "Bruneian",
        "Bulgarian",
        "Burkinabe",
        "Burmese",
        "Burundian",
        "Cambodian",
        "Cameroonian",
        "Canadian",
        "Cape Verdean",
        "Central African",
        "Chadian",
        "Chilean",
        "Chinese",
        "Colombian",
        "Comoran",
        "Congolese",
        "Costa Rican",
        "Croatian",
        "Cuban",
        "Cypriot",
        "Czech",
        "Danish",
        "Djibouti",
        "Dominican",
        "Dutch",
        "East Timorese",
        "Ecuadorean",
        "Egyptian",
        "Emirian",
        "Equatorial Guinean",
        "Eritrean",
        "Estonian",
        "Ethiopian",
        "Fijian",
        "Filipino",
        "Finnish",
        "French",
        "Gabonese",
        "Gambian",
        "Georgian",
        "German",
        "Ghanaian",
        "Greek",
        "Grenadian",
        "Guatemalan",
        "Guinea-Bissauan",
        "Guinean",
        "Guyanese",
        "Haitian",
        "Herzegovinian",
        "Honduran",
        "Hungarian",
        "Icelander",
        "Indian",
        "Indonesian",
        "Iranian",
        "Iraqi",
        "Irish",
        "Italian",
        "Ivorian",
        "Jamaican",
        "Japanese",
        "Jordanian",
        "Kazakhstani",
        "Kenyan",
        "Kittian and Nevisian",
        "Kuwaiti",
        "Kyrgyz",
        "Laotian",
        "Latvian",
        "Lebanese",
        "Liberian",
        "Libyan",
        "Liechtensteiner",
        "Lithuanian",
        "Luxembourger",
        "Macedonian",
        "Malagasy",
        "Malawian",
        "Malaysian",
        "Maldivan",
        "Malian",
        "Maltese",
        "Marshallese",
        "Mauritanian",
        "Mauritian",
        "Mexican",
        "Micronesian",
        "Moldovan",
        "Monacan",
        "Mongolian",
        "Moroccan",
        "Mosotho",
        "Motswana",
        "Mozambican",
        "Namibian",
        "Nauruan",
        "Nepalese",
        "New Zealander",
        "Ni-Vanuatu",
        "Nicaraguan",
        "Nigerien",
        "North Korean",
        "Northern Irish",
        "Norwegian",
        "Omani",
        "Pakistani",
        "Palauan",
        "Palestinian",
        "Panamanian",
        "Papua New Guinean",
        "Paraguayan",
        "Peruvian",
        "Polish",
        "Portuguese",
        "Qatari",
        "Romanian",
        "Russian",
        "Rwandan",
        "Saint Lucian",
        "Salvadoran",
        "Samoan",
        "San Marinese",
        "Sao Tomean",
        "Saudi",
        "Scottish",
        "Senegalese",
        "Serbian",
        "Seychellois",
        "Sierra Leonean",
        "Singaporean",
        "Slovakian",
        "Slovenian",
        "Solomon Islander",
        "Somali",
        "South African",
        "South Korean",
        "Spanish",
        "Sri Lankan",
        "Sudanese",
        "Surinamer",
        "Swazi",
        "Swedish",
        "Swiss",
        "Syrian",
        "Taiwanese",
        "Tajik",
        "Tanzanian",
        "Thai",
        "Togolese",
        "Tongan",
        "Trinidadian or Tobagonian",
        "Tunisian",
        "Turkish",
        "Tuvaluan",
        "Ugandan",
        "Ukrainian",
        "Uruguayan",
        "Uzbekistani",
        "Venezuelan",
        "Vietnamese",
        "Welsh",
        "Yemenite",
        "Zambian",
        "Zimbabwean"
    ],
    title_ar: [
        "أفغاني",
        "ألباني",
        "جزائري",
        "أمريكي",
        "أندوري",
        "أنغولي",
        "انتيغوا",
        "أرجنتيني",
        "أرميني",
        "أسترالي",
        "نمساوي",
        "أذربيجاني",
        "باهامى",
        "بحريني",
        "بنجلاديشي",
        "باربادوسي",
        "بربودا",
        "بوتسواني",
        "بيلاروسي",
        "بلجيكي",
        "بليزي",
        "بنيني",
        "بوتاني",
        "بوليفي",
        "بوسني",
        "برازيلي",
        "بريطاني",
        "بروناى",
        "بلغاري",
        "بوركيني",
        "بورمي",
        "بوروندي",
        "كمبودي",
        "كاميروني",
        "كندي",
        "االرأس الأخضر",
        "وسط أفريقيا",
        "تشادي",
        "شيلي",
        "صينى",
        "كولومبي",
        "جزر القمر",
        "كونغولي",
        "كوستاريكي",
        "كرواتية",
        "كوبي",
        "قبرصي",
        "تشيكي",
        "دانماركي",
        "جيبوتي",
        "دومينيكاني",
        "هولندي",
        "تيموري شرقي",
        "اكوادوري",
        "مصري",
        "إماراتي",
        "غيني  استوائي",
        "إريتري",
        "إستوني",
        "حبشي",
        "فيجي",
        "فلبيني",
        "فنلندي",
        "فرنسي",
        "جابوني",
        "غامبيي",
        "جورجي",
        "ألماني",
        "غاني",
        "إغريقي",
        "جرينادي",
        "غواتيمالي",
        "غيني بيساوي",
        "غيني",
        "جوياني",
        "هايتي",
        "هرسكي",
        "هندوراسي",
        "هنغاري",
        "إيسلندي",
        "هندي",
        "إندونيسي",
        "إيراني",
        "عراقي",
        "إيرلندي",
        "إيطالي",
        "إفواري",
        "جامايكي",
        "ياباني",
        "أردني",
        "كازاخستاني",
        "كيني",
        "كيتياني ونيفيسياني",
        "كويتي",
        "قيرغيزستان",
        "لاوسي",
        "لاتفي",
        "لبناني",
        "ليبيري",
        "ليبي",
        "ليختنشتايني",
        "لتواني",
        "لكسمبرغي",
        "مقدوني",
        "مدغشقري",
        "مالاوى",
        "ماليزي",
        "مالديفي",
        "مالي",
        "مالطي",
        "مارشالي",
        "موريتاني",
        "موريشيوسي",
        "مكسيكي",
        "ميكرونيزي",
        "مولدوفي",
        "موناكو",
        "منغولي",
        "مغربي",
        "ليسوتو",
        "لتسواني",
        "موزمبيقي",
        "ناميبي",
        "ناورو",
        "نيبالي",
        "نيوزيلندي",
        "ني فانواتي",
        "نيكاراغوا",
        "نيجري",
        "كوري شمالي",
        "إيرلندي شمالي",
        "نرويجي",
        "عماني",
        "باكستاني",
        "بالاوي",
        "فلسطيني",
        "بنمي",
        "بابوا غينيا الجديدة",
        "باراغواياني",
        "بيروفي",
        "بولندي",
        "برتغالي",
        "قطري",
        "روماني",
        "روسي",
        "رواندي",
        "لوسياني",
        "سلفادوري",
        "ساموايان",
        "سان مارينيز",
        "ساو توميان",
        "سعودي",
        "سكتلندي",
        "سنغالي",
        "صربي",
        "سيشلي",
        "سيرا ليوني",
        "سنغافوري",
        "سلوفاكي",
        "سلوفيني",
        "جزر سليمان",
        "صومالي",
        "جنوب افريقيي",
        "كوري جنوبي",
        "إسباني",
        "سري لانكي",
        "سوداني",
        "سورينامي",
        "سوازي",
        "سويدي",
        "سويسري",
        "سوري",
        "تايواني",
        "طاجيكي",
        "تنزاني",
        "التايلاندي",
        "توغواني",
        "تونجاني",
        "ترينيدادي أو توباغوني",
        "تونسي",
        "تركي",
        "توفالي",
        "أوغندي",
        "أوكراني",
        "أوروجواي",
        "أوزبكستاني",
        "فنزويلي",
        "فيتنامي",
        "ويلزي",
        "يمني",
        "زامبي",
        "زيمبابوي"
    ]
}